# main.yml
name: kubernetes CI/CD
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
    - name: checkout source code
      uses: actions/checkout@main

    - name: Build the Docker image
      run: docker build . -t mnhyuntaekim/app:$GITHUB_RUN_NUMBER

    - name: login
      run: docker login -u mnhyuntaekim -p $PASSWORD
      env:
        PASSWORD: ${{ secrets.PASSWORD }}

    - name: Push the Docker image
      run: docker push mnhyuntaekim/app:$GITHUB_RUN_NUMBER

    - uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBECONFIG }}
      id: setcontext

    - name: deploy
      run: kubectl get set image deployment app app=mnhyuntaekim/app:$GITHUB_RUN_NUMBER
